
--Rem

--country
INSERT INTO country (country_code, country_kr_name, country_en_name) VALUES(1,'태국','tai');
INSERT INTO country (country_code, country_kr_name, country_en_name) VALUES(2,'베트남','VIETNAM');
INSERT INTO country (country_code, country_kr_name, country_en_name) VALUES(3,'필리핀','phil');
--city 
INSERT INTO city VALUES( 1, '방콕', 'Bangkok',1);
INSERT INTO city VALUES( 2,'카오산', 'kaosan',1);
INSERT INTO city VALUES( 3,'담헤이', 'dam',1);
INSERT INTO city VALUES( 4,'호치민', 'hochi',2);
INSERT INTO city VALUES( 5, '달랏', 'dalot',2);
INSERT INTO city VALUES( 6,'하노이', 'Hanoi',2);
INSERT INTO city VALUES( 7,'아시아티크', 'asiateak',1);
INSERT INTO city VALUES( 8,'마닐라', 'Carti',3);


--market
INSERT INTO market VALUES(1,'카오산로드','gwang',0.58,0.699,'info',2);
INSERT INTO market VALUES(2,'짝두짝시장','jjak',0.342,0.785,'info',1);
INSERT INTO market VALUES(3,'깔티마시장','jjak',0.342,0.785,'info',8);



REM 베트남 임시데이터 
--USERINFO
INSERT INTO USERINFO (USER_ID, USER_PASSWORD, USER_NAME, AUTHORITY) VALUES ('admin', '12345', '관리자', '1');


--Country 데이터 5행에서 삽입했으므로 중복되므로 생략하고 넘어가주세요
INSERT INTO COUNTRY (country_code,COUNTRY_KR_NAME, COUNTRY_EN_NAME) VALUES (1,'베트남','VIETNAM');
--CITY 데이터  11~13행에서 삽입했으므로 중복되므로 생략하고 넘어가주세요
INSERT INTO CITY (CITY_NUMBER,CITY_KR_NAME, CITY_EN_NAME, COUNTRY_CODE)VALUES (4,'호치민', 'Ho Chi Minh', 2);
INSERT INTO CITY (CITY_NUMBER,CITY_KR_NAME, CITY_EN_NAME, COUNTRY_CODE)VALUES (5,'달랏', 'Dalat', 2);
INSERT INTO CITY (CITY_NUMBER,CITY_KR_NAME, CITY_EN_NAME, COUNTRY_CODE)VALUES (6,'하노이', 'Hanoi', 2);


--MARKET 데이터
INSERT INTO MARKET (MARKET_NUMBER, MARKET_KR_NAME, MARKET_EN_NAME, LATITUDE, LONGITUDE, market_info, city_number) VALUES (4, '벤탄','Ben Thanh',10.7919695,106.6250147, '여기는 벤탄시장입니다.', 4);
INSERT INTO MARKET (MARKET_NUMBER, MARKET_KR_NAME, MARKET_EN_NAME, LATITUDE, LONGITUDE, market_info,city_number) VALUES (5, '달랏','Dalat',11.9428556,108.4346737, '여기는 달랏시장입니다.', 5);
INSERT INTO MARKET (MARKET_NUMBER, MARKET_KR_NAME, MARKET_EN_NAME, LATITUDE, LONGITUDE, market_info,city_number) VALUES (6, '동쑤언','Dong Xuan',21.0345583,105.8484525, '여기는 동쑤언시장입니다.', 6);

--PRODUCT 데이터
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CHECK_STATUS, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (1,'바나나',2000,to_date('2020-11-24', 'RRRR-MM-DD'),80, 1, 4,4,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CHECK_STATUS, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (2,'사과',500,to_date('2020-11-25', 'RRRR-MM-DD'),50, 0, 4,4,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CHECK_STATUS, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (3,'물',1200,to_date('2020-11-26', 'RRRR-MM-DD'),10, 1, 4,4,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CHECK_STATUS, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (4,'망고',2870,to_date('2020-11-27', 'RRRR-MM-DD'),9, 1, 4,4,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CHECK_STATUS, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (5,'라면',1080,to_date('2020-11-28', 'RRRR-MM-DD'),1, 1, 4,4,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CHECK_STATUS, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (6,'커피포트',38900,to_date('2020-11-29', 'RRRR-MM-DD'),8, 0, 4,4,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CHECK_STATUS, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (7,'우동',5000,to_date('2020-11-30', 'RRRR-MM-DD'),15, 1, 4,4,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CHECK_STATUS, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (8,'커피',2160,to_date('2020-12-01', 'RRRR-MM-DD'),152, 1, 4,4,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CHECK_STATUS, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (9,'요거트',220,to_date('2020-12-02', 'RRRR-MM-DD'),157, 1, 4,4,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CHECK_STATUS, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (10,'인형',10100,to_date('2020-12-03', 'RRRR-MM-DD'),111, 0, 4,4,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CHECK_STATUS, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (11,'스타애플',80,to_date('2020-12-04', 'RRRR-MM-DD'),26, 1, 4,4,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CHECK_STATUS, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (12,'커스타드 애플',250,to_date('2020-12-05', 'RRRR-MM-DD'),258, 1, 4,4,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CHECK_STATUS, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (13,'바나나',1810,to_date('2020-12-06', 'RRRR-MM-DD'),17, 1, 5,5,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CHECK_STATUS, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (14,'사과',300,to_date('2020-12-07', 'RRRR-MM-DD'),89, 1, 5,5,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CHECK_STATUS, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (15,'물',800,to_date('2020-12-08', 'RRRR-MM-DD'),69, 0, 5,5,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CHECK_STATUS, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (16,'반미',1500,to_date('2020-12-09', 'RRRR-MM-DD'),92, 1, 5,5,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CHECK_STATUS, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (17,'볶음밥',1320,to_date('2020-12-10', 'RRRR-MM-DD'),100, 1, 5,5,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CHECK_STATUS, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (18,'닭',4500,to_date('2020-12-11', 'RRRR-MM-DD'),871, 1, 5,5,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CHECK_STATUS, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (19,'우렁이찜',7110,to_date('2020-12-12', 'RRRR-MM-DD'),50, 1, 5,5,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CHECK_STATUS, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (20,'쌀국수',800,to_date('2020-12-13', 'RRRR-MM-DD'),33, 0, 5,5,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CHECK_STATUS, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (21,'인형',800,to_date('2020-12-14', 'RRRR-MM-DD'),120, 1, 5,5,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CHECK_STATUS, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (22,'망고주스',320,to_date('2020-12-15', 'RRRR-MM-DD'),77, 1, 5,5,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CHECK_STATUS, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (23,'바나나',800,to_date('2020-12-16', 'RRRR-MM-DD'),0, 1, 6,6,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CHECK_STATUS, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (24,'사과',450,to_date('2020-12-17', 'RRRR-MM-DD'),0, 0, 6,6,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CHECK_STATUS, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (25,'물',970,to_date('2020-12-18', 'RRRR-MM-DD'),0, 1, 6,6,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CHECK_STATUS, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (26,'쌀국수',1210,to_date('2020-12-19', 'RRRR-MM-DD'),0, 1, 6,6,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CHECK_STATUS, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (27,'망고',1800,to_date('2020-12-20', 'RRRR-MM-DD'),0, 1, 6,6,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CHECK_STATUS, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (28,'커스터드 애플',500,to_date('2020-12-21', 'RRRR-MM-DD'),0, 1, 6,6,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CHECK_STATUS, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (29,'당근',110,to_date('2020-12-22', 'RRRR-MM-DD'),0, 0, 6,6,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CHECK_STATUS, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (30,'코코넛',90,to_date('2020-12-23', 'RRRR-MM-DD'),0, 1, 6,6,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CHECK_STATUS, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (31,'코코넛 가루',250,to_date('2020-12-24', 'RRRR-MM-DD'),0, 0, 6,6,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CHECK_STATUS, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (32,'말린 새우',6520,to_date('2020-12-25', 'RRRR-MM-DD'),990, 1, 6,6,'admin');


COMMIT;