--Rem

--country
INSERT INTO country VALUES(1,'태국','tai',systimestamp);
INSERT INTO country VALUES(2,'베트남','VIETNAM',to_timestamp('2020-11-24:11:29:53', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO country VALUES(3,'필리핀','phil',systimestamp);
--city 
INSERT INTO city VALUES( 1, '방콕', 'Bangkok',1);
INSERT INTO city VALUES( 2,'카오산', 'kaosan',1);
INSERT INTO city VALUES( 3,'담헤이', 'dam',1);
INSERT INTO city VALUES( 4,'호치민', 'hochi',2);
INSERT INTO city VALUES( 5, '달랏', 'dalot',2);
INSERT INTO city VALUES( 6,'하노이', 'Hanoi',2);
INSERT INTO city VALUES( 7,'아시아티크', 'asiateak',1);
INSERT INTO city VALUES( 8,'마닐라', 'Carti',3);


--market
INSERT INTO market VALUES(1,'카오산로드','gwang',0.58,0.699,'info',2);
INSERT INTO market VALUES(2,'짝두짝시장','jjak',0.342,0.785,'info',1);
INSERT INTO market VALUES(3,'깔티마시장','jjak',0.342,0.785,'info',8);



REM 베트남 임시데이터 
--USERINFO
INSERT INTO USERINFO (USER_ID, USER_PASSWORD, USER_NAME, AUTHORITY) VALUES ('admin', '12345', '관리자', '1');


--Country 데이터 5행에서 삽입했으므로 중복되므로 생략하고 넘어가주세요
INSERT INTO COUNTRY (country_code,COUNTRY_KR_NAME, COUNTRY_EN_NAME, COUNTRY_FLAG_IMG) VALUES (1,'베트남','VIETNAM',to_timestamp('2020-11-24:11:29:53', 'YYYY-MM-DD HH24:MI:SS'));
--CITY 데이터  11~13행에서 삽입했으므로 중복되므로 생략하고 넘어가주세요
INSERT INTO CITY (CITY_NUMBER,CITY_KR_NAME, CITY_EN_NAME, COUNTRY_CODE)VALUES (4,'호치민', 'Ho Chi Minh', 2);
INSERT INTO CITY (CITY_NUMBER,CITY_KR_NAME, CITY_EN_NAME, COUNTRY_CODE)VALUES (5,'달랏', 'Dalat', 2);
INSERT INTO CITY (CITY_NUMBER,CITY_KR_NAME, CITY_EN_NAME, COUNTRY_CODE)VALUES (6,'하노이', 'Hanoi', 2);


--MARKET 데이터
INSERT INTO MARKET (MARKET_NUMBER, MARKET_KR_NAME, MARKET_EN_NAME, LATITUDE, LONGITUDE, market_info, city_number) VALUES (4, '벤탄','Ben Thanh',10.7919695,106.6250147, '여기는 벤탄시장입니다.', 4);
INSERT INTO MARKET (MARKET_NUMBER, MARKET_KR_NAME, MARKET_EN_NAME, LATITUDE, LONGITUDE, market_info,city_number) VALUES (5, '달랏','Dalat',11.9428556,108.4346737, '여기는 달랏시장입니다.', 5);
INSERT INTO MARKET (MARKET_NUMBER, MARKET_KR_NAME, MARKET_EN_NAME, LATITUDE, LONGITUDE, market_info,city_number) VALUES (6, '동쑤언','Dong Xuan',21.0345583,105.8484525, '여기는 동쑤언시장입니다.', 6);

--PRODUCT 데이터
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (1,'바나나',2.01,to_date('2020-11-24', 'RRRR-MM-DD'),80,4,4,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (2,'사과',0.5,to_date('2020-11-25', 'RRRR-MM-DD'),50,4,4,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (3,'물',1.2,to_date('2020-11-26', 'RRRR-MM-DD'),10,4,4,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (4,'망고',2.87,to_date('2020-11-27', 'RRRR-MM-DD'),9,4,4,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (5,'라면',1.08,to_date('2020-11-28', 'RRRR-MM-DD'),1,4,4,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (6,'커피포트',38.9,to_date('2020-11-29', 'RRRR-MM-DD'),8,4,4,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (7,'우동',5,to_date('2020-11-30', 'RRRR-MM-DD'),15,4,4,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (8,'커피',2.16,to_date('2020-12-01', 'RRRR-MM-DD'),152,4,4,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (9,'요거트',0.22,to_date('2020-12-02', 'RRRR-MM-DD'),157,4,4,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (10,'인형',10.1,to_date('2020-12-03', 'RRRR-MM-DD'),111,4,4,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (11,'스타애플',0.08,to_date('2020-12-04', 'RRRR-MM-DD'),26,4,4,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (12,'커스타드 애플',0.25,to_date('2020-12-05', 'RRRR-MM-DD'),258,4,4,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (13,'바나나',1.81,to_date('2020-12-06', 'RRRR-MM-DD'),17,5,5,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (14,'사과',0.3,to_date('2020-12-07', 'RRRR-MM-DD'),89,5,5,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (15,'물',0.8,to_date('2020-12-08', 'RRRR-MM-DD'),69,5,5,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (16,'반미',1.5,to_date('2020-12-09', 'RRRR-MM-DD'),92,5,5,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (17,'볶음밥',1.32,to_date('2020-12-10', 'RRRR-MM-DD'),100,5,5,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (18,'닭',4.5,to_date('2020-12-11', 'RRRR-MM-DD'),871,5,5,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (19,'우렁이찜',7.11,to_date('2020-12-12', 'RRRR-MM-DD'),50,5,5,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (20,'쌀국수',0.8,to_date('2020-12-13', 'RRRR-MM-DD'),33,5,5,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (21,'인형',0.8,to_date('2020-12-14', 'RRRR-MM-DD'),120,5,5,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (22,'망고주스',0.32,to_date('2020-12-15', 'RRRR-MM-DD'),77,5,5,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (23,'바나나',0.8,to_date('2020-12-16', 'RRRR-MM-DD'),0,6,6,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (24,'사과',0.45,to_date('2020-12-17', 'RRRR-MM-DD'),0,6,6,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (25,'물',0.97,to_date('2020-12-18', 'RRRR-MM-DD'),0,6,6,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (26,'쌀국수',1.21,to_date('2020-12-19', 'RRRR-MM-DD'),0,6,6,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (27,'망고',1.8,to_date('2020-12-20', 'RRRR-MM-DD'),0,6,6,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (28,'커스터드 애플',0.55,to_date('2020-12-21', 'RRRR-MM-DD'),0,6,6,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (29,'당근',0.11,to_date('2020-12-22', 'RRRR-MM-DD'),0,6,6,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (30,'코코넛',0.09,to_date('2020-12-23', 'RRRR-MM-DD'),0,6,6,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (31,'코코넛 가루',0.25,to_date('2020-12-24', 'RRRR-MM-DD'),0,6,6,'admin');
INSERT INTO PRODUCT (PRODUCT_NUMBER,PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DATE, SEQUENCE, CITY_NUMBER, MARKET_NUMBER, USER_ID) VALUES (32,'말린 새우',6.52,to_date('2020-12-25', 'RRRR-MM-DD'),990,6,6,'admin');


COMMIT;